title: "Event contributor list update request"
body:
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
        - label: I won't stop you if you check this one, too
